### ISSUE TITLE
Training dataset in data2vec-aqc

### ISSUE THREAD

**Issue by malarvizhimuthuramalingam** [Speech-Lab-IITM/data2vec-aqc#2]
speechlab@speechlab-HP-Pro-Tower-400-G9-PCI-Desktop-PC:~/data2vec-aqc$ python fairseq_cli/hydra_train.py -m --config-dir examples/data2vec/config/audio/pretraining --config-name base_librispeech task.data=examples/train.tsv common.user_dir=examples/data2vec
Traceback (most recent call last):
  File "/home/speechlab/data2vec-aqc/fairseq_cli/hydra_train.py", line 10, in <module>
    import hydra
  File "/home/speechlab/anaconda3/lib/python3.11/site-packages/hydra/__init__.py", line 5, in <module>
    from hydra import utils
  File "/home/speechlab/anaconda3/lib/python3.11/site-packages/hydra/utils.py", line 10, in <module>
    from hydra._internal.utils import (
  File "/home/speechlab/anaconda3/lib/python3.11/site-packages/hydra/_internal/utils.py", line 21, in <module>
    from hydra.core.utils import get_valid_filename, split_config_path
  File "/home/speechlab/anaconda3/lib/python3.11/site-packages/hydra/core/utils.py", line 19, in <module>
    from hydra.core.hydra_config import HydraConfig
  File "/home/speechlab/anaconda3/lib/python3.11/site-packages/hydra/core/hydra_config.py", line 6, in <module>
    from hydra.conf import HydraConf
  File "/home/speechlab/anaconda3/lib/python3.11/site-packages/hydra/conf/__init__.py", line 62, in <module>
    class JobConf:
  File "/home/speechlab/anaconda3/lib/python3.11/site-packages/hydra/conf/__init__.py", line 87, in JobConf
    @dataclass
     ^^^^^^^^^
  File "/home/speechlab/anaconda3/lib/python3.11/dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/speechlab/anaconda3/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/speechlab/anaconda3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/speechlab/anaconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory

**Comment by malarvizhimuthuramalingam** [comment]
Trained for our own data ,tsv files were created but not able to start training due to above issues
